### ISSUE TITLE
pvp not start properly

### ISSUE THREAD

**Issue by qsef1256** [qsef1256/DiaBot#7]
```
C:\Users\202030231\DiaProjects\DiaBot\diabot.js:214
    botOutput(username, 'Start PVP with ' + player.username)
                                            ^

ReferenceError: player is not defined
    at EventEmitter.botCommand (C:\Users\202030231\DiaProjects\DiaBot\diabot.js:214:45)
    at EventEmitter.emit (node:events:513:28)
    at EventEmitter.<anonymous> (C:\Users\202030231\DiaProjects\DiaBot\node_modules\mineflayer\lib\plugins\chat.js:85:13)
    at EventEmitter.emit (node:events:513:28)
    at Client.<anonymous> (C:\Users\202030231\DiaProjects\DiaBot\node_modules\mineflayer\lib\plugins\chat.js:120:9)
    at Client.emit (node:events:513:28)
    at FullPacketParser.<anonymous> (C:\Users\202030231\DiaProjects\DiaBot\node_modules\minecraft-protocol\src\client.js:91:12)
    at FullPacketParser.emit (node:events:513:28)
    at addChunk (C:\Users\202030231\DiaProjects\DiaBot\node_modules\protodef\node_modules\readable-stream\lib\_stream_readable.js:298:12)
    at readableAddChunk (C:\Users\202030231\DiaProjects\DiaBot\node_modules\protodef\node_modules\readable-stream\lib\_stream_readable.js:280:11)
```

**Comment by qsef1256** [comment]
fixed by 28809fb96f348ae743fbcb767df5a090936a3a0e
