### ISSUE TITLE
/webinv not working

### ISSUE THREAD

**Issue by qsef1256** [qsef1256/DiaBot#8]
```
ReferenceError: viewer is not defined
    at botCommand (C:\Users\202030231\DiaProjects\DiaBot\diabot.js:158:35)
    at Interface.<anonymous> (C:\Users\202030231\DiaProjects\DiaBot\diabot.js:50:3)
    at Interface.emit (node:events:513:28)
    at Interface._onLine (node:readline:491:10)
    at Interface._line (node:readline:868:8)
    at Interface._ttyWrite (node:readline:1220:14)
    at ReadStream.onkeypress (node:readline:291:10)
    at ReadStream.emit (node:events:513:28)
    at emitKeys (node:internal/readline/utils:357:14)
    at emitKeys.next (<anonymous>)
```
`viewer` 가 정의되지 않아서 생긴 문제로 확인

**Comment by qsef1256** [comment]
Not reproduce in latest
